version: '3'
services:
  voice_to_text:
    build: 
      context: .
      dockerfile: dockerfile
    image: marvinhris/vtt_fw:flask_${MODEL_SIZE}
    env_file:
      - .env
    container_name: ${CONTAINER_NAME}
    stdin_open: true
    tty: true
    restart: ${RESTART}
    deploy:
      resources:
        limits:
          memory: ${MEMORY}
    memswap_limit: ${SWAP_LIMIT}
    expose:
      - ${EXPOSE_PORT}
    ports:
      - ${PORT}:${EXPOSE_PORT}
    command: >
      bash -c "gunicorn --workers=${WORKER_TOTAL} --threads=${THREADS} --bind=${HOST}:${EXPOSE_PORT} --worker-class=${WORKER} --timeout=${TIMEOUT} wsgi:server"

